/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as OngoingRouteImport } from './routes/ongoing'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as FeatureRequestsRouteImport } from './routes/feature-requests'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as NovelsSlugRouteImport } from './routes/novels.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuthorsUsernameRouteImport } from './routes/authors.$username'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated.wallet'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated.library'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as NovelsSlugIndexRouteImport } from './routes/novels.$slug.index'
import { Route as AuthenticatedSupportIndexRouteImport } from './routes/_authenticated.support.index'
import { Route as AuthenticatedAuthorIndexRouteImport } from './routes/_authenticated.author.index'
import { Route as NovelsSlugChapterRouteImport } from './routes/novels.$slug.$chapter'
import { Route as AuthenticatedSupportIdRouteImport } from './routes/_authenticated.support.$id'
import { Route as AuthenticatedAuthorApplyRouteImport } from './routes/_authenticated.author.apply'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAuthorNovelsNewRouteImport } from './routes/_authenticated.author.novels.new'
import { Route as AuthenticatedAuthorNovelsIdRouteImport } from './routes/_authenticated.author.novels.$id'
import { Route as AuthenticatedAuthorNovelsIdChaptersNewRouteImport } from './routes/_authenticated.author.novels.$id.chapters.new'
import { Route as AuthenticatedAuthorNovelsIdChaptersChapterIdRouteImport } from './routes/_authenticated.author.novels.$id.chapters.$chapterId'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingRoute = OngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureRequestsRoute = FeatureRequestsRouteImport.update({
  id: '/feature-requests',
  path: '/feature-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsSlugRoute = NovelsSlugRouteImport.update({
  id: '/novels/$slug',
  path: '/novels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsUsernameRoute = AuthorsUsernameRouteImport.update({
  id: '/authors/$username',
  path: '/authors/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NovelsSlugIndexRoute = NovelsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovelsSlugRoute,
} as any)
const AuthenticatedSupportIndexRoute =
  AuthenticatedSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuthorIndexRoute =
  AuthenticatedAuthorIndexRouteImport.update({
    id: '/author/',
    path: '/author/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const NovelsSlugChapterRoute = NovelsSlugChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => NovelsSlugRoute,
} as any)
const AuthenticatedSupportIdRoute = AuthenticatedSupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthorApplyRoute =
  AuthenticatedAuthorApplyRouteImport.update({
    id: '/author/apply',
    path: '/author/apply',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAuthorNovelsNewRoute =
  AuthenticatedAuthorNovelsNewRouteImport.update({
    id: '/author/novels/new',
    path: '/author/novels/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuthorNovelsIdRoute =
  AuthenticatedAuthorNovelsIdRouteImport.update({
    id: '/author/novels/$id',
    path: '/author/novels/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuthorNovelsIdChaptersNewRoute =
  AuthenticatedAuthorNovelsIdChaptersNewRouteImport.update({
    id: '/chapters/new',
    path: '/chapters/new',
    getParentRoute: () => AuthenticatedAuthorNovelsIdRoute,
  } as any)
const AuthenticatedAuthorNovelsIdChaptersChapterIdRoute =
  AuthenticatedAuthorNovelsIdChaptersChapterIdRouteImport.update({
    id: '/chapters/$chapterId',
    path: '/chapters/$chapterId',
    getParentRoute: () => AuthenticatedAuthorNovelsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/completed': typeof CompletedRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/feature-requests': typeof FeatureRequestsRoute
  '/latest': typeof LatestRoute
  '/ongoing': typeof OngoingRoute
  '/popular': typeof PopularRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/authors/$username': typeof AuthorsUsernameRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/novels/$slug': typeof NovelsSlugRouteWithChildren
  '/pages/$slug': typeof PagesSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/author/apply': typeof AuthenticatedAuthorApplyRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/novels/$slug/$chapter': typeof NovelsSlugChapterRoute
  '/author/': typeof AuthenticatedAuthorIndexRoute
  '/support/': typeof AuthenticatedSupportIndexRoute
  '/novels/$slug/': typeof NovelsSlugIndexRoute
  '/author/novels/$id': typeof AuthenticatedAuthorNovelsIdRouteWithChildren
  '/author/novels/new': typeof AuthenticatedAuthorNovelsNewRoute
  '/author/novels/$id/chapters/$chapterId': typeof AuthenticatedAuthorNovelsIdChaptersChapterIdRoute
  '/author/novels/$id/chapters/new': typeof AuthenticatedAuthorNovelsIdChaptersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/completed': typeof CompletedRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/feature-requests': typeof FeatureRequestsRoute
  '/latest': typeof LatestRoute
  '/ongoing': typeof OngoingRoute
  '/popular': typeof PopularRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/authors/$username': typeof AuthorsUsernameRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/auth': typeof AuthIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/author/apply': typeof AuthenticatedAuthorApplyRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/novels/$slug/$chapter': typeof NovelsSlugChapterRoute
  '/author': typeof AuthenticatedAuthorIndexRoute
  '/support': typeof AuthenticatedSupportIndexRoute
  '/novels/$slug': typeof NovelsSlugIndexRoute
  '/author/novels/$id': typeof AuthenticatedAuthorNovelsIdRouteWithChildren
  '/author/novels/new': typeof AuthenticatedAuthorNovelsNewRoute
  '/author/novels/$id/chapters/$chapterId': typeof AuthenticatedAuthorNovelsIdChaptersChapterIdRoute
  '/author/novels/$id/chapters/new': typeof AuthenticatedAuthorNovelsIdChaptersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/completed': typeof CompletedRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/feature-requests': typeof FeatureRequestsRoute
  '/latest': typeof LatestRoute
  '/ongoing': typeof OngoingRoute
  '/popular': typeof PopularRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/authors/$username': typeof AuthorsUsernameRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/novels/$slug': typeof NovelsSlugRouteWithChildren
  '/pages/$slug': typeof PagesSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/author/apply': typeof AuthenticatedAuthorApplyRoute
  '/_authenticated/support/$id': typeof AuthenticatedSupportIdRoute
  '/novels/$slug/$chapter': typeof NovelsSlugChapterRoute
  '/_authenticated/author/': typeof AuthenticatedAuthorIndexRoute
  '/_authenticated/support/': typeof AuthenticatedSupportIndexRoute
  '/novels/$slug/': typeof NovelsSlugIndexRoute
  '/_authenticated/author/novels/$id': typeof AuthenticatedAuthorNovelsIdRouteWithChildren
  '/_authenticated/author/novels/new': typeof AuthenticatedAuthorNovelsNewRoute
  '/_authenticated/author/novels/$id/chapters/$chapterId': typeof AuthenticatedAuthorNovelsIdChaptersChapterIdRoute
  '/_authenticated/author/novels/$id/chapters/new': typeof AuthenticatedAuthorNovelsIdChaptersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/about'
    | '/completed'
    | '/contact'
    | '/dashboard'
    | '/dmca'
    | '/faq'
    | '/feature-requests'
    | '/latest'
    | '/ongoing'
    | '/popular'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/vip'
    | '/admin'
    | '/library'
    | '/notifications'
    | '/profile'
    | '/wallet'
    | '/api/sitemap.xml'
    | '/auth/reset-password'
    | '/authors/$username'
    | '/categories/$slug'
    | '/novels/$slug'
    | '/pages/$slug'
    | '/auth/'
    | '/categories/'
    | '/admin/dashboard'
    | '/author/apply'
    | '/support/$id'
    | '/novels/$slug/$chapter'
    | '/author/'
    | '/support/'
    | '/novels/$slug/'
    | '/author/novels/$id'
    | '/author/novels/new'
    | '/author/novels/$id/chapters/$chapterId'
    | '/author/novels/$id/chapters/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/about'
    | '/completed'
    | '/contact'
    | '/dashboard'
    | '/dmca'
    | '/faq'
    | '/feature-requests'
    | '/latest'
    | '/ongoing'
    | '/popular'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/vip'
    | '/admin'
    | '/library'
    | '/notifications'
    | '/profile'
    | '/wallet'
    | '/api/sitemap.xml'
    | '/auth/reset-password'
    | '/authors/$username'
    | '/categories/$slug'
    | '/pages/$slug'
    | '/auth'
    | '/categories'
    | '/admin/dashboard'
    | '/author/apply'
    | '/support/$id'
    | '/novels/$slug/$chapter'
    | '/author'
    | '/support'
    | '/novels/$slug'
    | '/author/novels/$id'
    | '/author/novels/new'
    | '/author/novels/$id/chapters/$chapterId'
    | '/author/novels/$id/chapters/new'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_authenticated'
    | '/about'
    | '/completed'
    | '/contact'
    | '/dashboard'
    | '/dmca'
    | '/faq'
    | '/feature-requests'
    | '/latest'
    | '/ongoing'
    | '/popular'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/vip'
    | '/_authenticated/admin'
    | '/_authenticated/library'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/wallet'
    | '/api/sitemap.xml'
    | '/auth/reset-password'
    | '/authors/$username'
    | '/categories/$slug'
    | '/novels/$slug'
    | '/pages/$slug'
    | '/auth/'
    | '/categories/'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/author/apply'
    | '/_authenticated/support/$id'
    | '/novels/$slug/$chapter'
    | '/_authenticated/author/'
    | '/_authenticated/support/'
    | '/novels/$slug/'
    | '/_authenticated/author/novels/$id'
    | '/_authenticated/author/novels/new'
    | '/_authenticated/author/novels/$id/chapters/$chapterId'
    | '/_authenticated/author/novels/$id/chapters/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CompletedRoute: typeof CompletedRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DmcaRoute: typeof DmcaRoute
  FaqRoute: typeof FaqRoute
  FeatureRequestsRoute: typeof FeatureRequestsRoute
  LatestRoute: typeof LatestRoute
  OngoingRoute: typeof OngoingRoute
  PopularRoute: typeof PopularRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  VipRoute: typeof VipRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthorsUsernameRoute: typeof AuthorsUsernameRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  NovelsSlugRoute: typeof NovelsSlugRouteWithChildren
  PagesSlugRoute: typeof PagesSlugRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing': {
      id: '/ongoing'
      path: '/ongoing'
      fullPath: '/ongoing'
      preLoaderRoute: typeof OngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-requests': {
      id: '/feature-requests'
      path: '/feature-requests'
      fullPath: '/feature-requests'
      preLoaderRoute: typeof FeatureRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/$slug': {
      id: '/novels/$slug'
      path: '/novels/$slug'
      fullPath: '/novels/$slug'
      preLoaderRoute: typeof NovelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$username': {
      id: '/authors/$username'
      path: '/authors/$username'
      fullPath: '/authors/$username'
      preLoaderRoute: typeof AuthorsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/novels/$slug/': {
      id: '/novels/$slug/'
      path: '/'
      fullPath: '/novels/$slug/'
      preLoaderRoute: typeof NovelsSlugIndexRouteImport
      parentRoute: typeof NovelsSlugRoute
    }
    '/_authenticated/support/': {
      id: '/_authenticated/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AuthenticatedSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/author/': {
      id: '/_authenticated/author/'
      path: '/author'
      fullPath: '/author/'
      preLoaderRoute: typeof AuthenticatedAuthorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/novels/$slug/$chapter': {
      id: '/novels/$slug/$chapter'
      path: '/$chapter'
      fullPath: '/novels/$slug/$chapter'
      preLoaderRoute: typeof NovelsSlugChapterRouteImport
      parentRoute: typeof NovelsSlugRoute
    }
    '/_authenticated/support/$id': {
      id: '/_authenticated/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof AuthenticatedSupportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/author/apply': {
      id: '/_authenticated/author/apply'
      path: '/author/apply'
      fullPath: '/author/apply'
      preLoaderRoute: typeof AuthenticatedAuthorApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/author/novels/new': {
      id: '/_authenticated/author/novels/new'
      path: '/author/novels/new'
      fullPath: '/author/novels/new'
      preLoaderRoute: typeof AuthenticatedAuthorNovelsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/author/novels/$id': {
      id: '/_authenticated/author/novels/$id'
      path: '/author/novels/$id'
      fullPath: '/author/novels/$id'
      preLoaderRoute: typeof AuthenticatedAuthorNovelsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/author/novels/$id/chapters/new': {
      id: '/_authenticated/author/novels/$id/chapters/new'
      path: '/chapters/new'
      fullPath: '/author/novels/$id/chapters/new'
      preLoaderRoute: typeof AuthenticatedAuthorNovelsIdChaptersNewRouteImport
      parentRoute: typeof AuthenticatedAuthorNovelsIdRoute
    }
    '/_authenticated/author/novels/$id/chapters/$chapterId': {
      id: '/_authenticated/author/novels/$id/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/author/novels/$id/chapters/$chapterId'
      preLoaderRoute: typeof AuthenticatedAuthorNovelsIdChaptersChapterIdRouteImport
      parentRoute: typeof AuthenticatedAuthorNovelsIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAuthorNovelsIdRouteChildren {
  AuthenticatedAuthorNovelsIdChaptersChapterIdRoute: typeof AuthenticatedAuthorNovelsIdChaptersChapterIdRoute
  AuthenticatedAuthorNovelsIdChaptersNewRoute: typeof AuthenticatedAuthorNovelsIdChaptersNewRoute
}

const AuthenticatedAuthorNovelsIdRouteChildren: AuthenticatedAuthorNovelsIdRouteChildren =
  {
    AuthenticatedAuthorNovelsIdChaptersChapterIdRoute:
      AuthenticatedAuthorNovelsIdChaptersChapterIdRoute,
    AuthenticatedAuthorNovelsIdChaptersNewRoute:
      AuthenticatedAuthorNovelsIdChaptersNewRoute,
  }

const AuthenticatedAuthorNovelsIdRouteWithChildren =
  AuthenticatedAuthorNovelsIdRoute._addFileChildren(
    AuthenticatedAuthorNovelsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedAuthorApplyRoute: typeof AuthenticatedAuthorApplyRoute
  AuthenticatedSupportIdRoute: typeof AuthenticatedSupportIdRoute
  AuthenticatedAuthorIndexRoute: typeof AuthenticatedAuthorIndexRoute
  AuthenticatedSupportIndexRoute: typeof AuthenticatedSupportIndexRoute
  AuthenticatedAuthorNovelsIdRoute: typeof AuthenticatedAuthorNovelsIdRouteWithChildren
  AuthenticatedAuthorNovelsNewRoute: typeof AuthenticatedAuthorNovelsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedAuthorApplyRoute: AuthenticatedAuthorApplyRoute,
  AuthenticatedSupportIdRoute: AuthenticatedSupportIdRoute,
  AuthenticatedAuthorIndexRoute: AuthenticatedAuthorIndexRoute,
  AuthenticatedSupportIndexRoute: AuthenticatedSupportIndexRoute,
  AuthenticatedAuthorNovelsIdRoute:
    AuthenticatedAuthorNovelsIdRouteWithChildren,
  AuthenticatedAuthorNovelsNewRoute: AuthenticatedAuthorNovelsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NovelsSlugRouteChildren {
  NovelsSlugChapterRoute: typeof NovelsSlugChapterRoute
  NovelsSlugIndexRoute: typeof NovelsSlugIndexRoute
}

const NovelsSlugRouteChildren: NovelsSlugRouteChildren = {
  NovelsSlugChapterRoute: NovelsSlugChapterRoute,
  NovelsSlugIndexRoute: NovelsSlugIndexRoute,
}

const NovelsSlugRouteWithChildren = NovelsSlugRoute._addFileChildren(
  NovelsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CompletedRoute: CompletedRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DmcaRoute: DmcaRoute,
  FaqRoute: FaqRoute,
  FeatureRequestsRoute: FeatureRequestsRoute,
  LatestRoute: LatestRoute,
  OngoingRoute: OngoingRoute,
  PopularRoute: PopularRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  VipRoute: VipRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthorsUsernameRoute: AuthorsUsernameRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  NovelsSlugRoute: NovelsSlugRouteWithChildren,
  PagesSlugRoute: PagesSlugRoute,
  AuthIndexRoute: AuthIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
